
try:
    pass # Donde estara la logica
except error as e:
    pass # Donde manejaremos los errores dentro de la logica
else:
    pass # Se ejecuta si no hay exepciones
finally:
    pass # siempre se ejecuta